namespace: ernstov
placeholder-err-test-1:
  defines: runnable
  containers:
    placeholder-err-test-1:
      build: .
  variables:
    password:
      env: ADMIN_PASSWORD
      type: string
      value: not-set
    user:
      env: ADMIN_USERNAME
      type: string
      value: admin
  services:
    webserver:
      container: placeholder-err-test-1
      port: 8080
      protocol: tcp
